#!/bin/zsh

#/usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1 &
flatpak run org.deskflow.deskflow/x86_64/master &
$HOME/AppImages/beeper.appimage --no-sandbox %U &
#ksnip &
flameshot &
sensible-browser &
qlipper &
rustdesk &
#killall kwalletd6 &
cortile &
#kdeconnect-indicator &
#/home/dkendall/AppImages/fantascenedynamicwallpaper.appimage %F --platform xcb
#(sleep 3 && wmctrl -c "RustDesk" -b add,hidden)
