#!/bin/zsh

/usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1 &
#ksnip &
flameshot &
#beeper --disable-gpu &
sensible-browser &
qlipper &
rustdesk &
#killall kwalletd6 &
cortile &
kdeconnect-indicator &
(sleep 3 && wmctrl -c "RustDesk" -b add,hidden)
