#!/bin/sh

# PolicyKit authentication agent
/usr/bin/lxqt-policykit-agent &

# Launch sensible-browser
sensible-browser &

# Launch Diodon clipboard manager
diodon &

# Launch RustDesk with tray icon
rustdesk --tray &

# Launch Ksnip screenshot tool
ksnip &
